services:
  # 后端 FastAPI 业务容器
  backend:
    container_name: supermew-backend
    build:
      context: ../..
      dockerfile: deploy/prod/Dockerfile.backend
    restart: always
    env_file:
      - ../../.env
    ports:
      - "18000:18000"

  # 前端 Vue3 + Nginx 容器
  frontend:
    container_name: supermew-frontend
    build:
      context: ../..
      dockerfile: deploy/prod/Dockerfile.frontend
    restart: always
    ports:
      - "18089:18089"
    depends_on:
      - backend
